
package MemoryGame;

import java.io.BufferedWriter;
import java.io.FileWriter;

public class GameOver extends javax.swing.JFrame {
   
    
    public GameOver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username_txtbox = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        viewLeaderboardButton = new javax.swing.JButton();
        GameOverInfo = new javax.swing.JLabel();
        noSaveButton = new javax.swing.JButton();
        gameOverLabel = new javax.swing.JLabel();
        finalScoreLabel = new javax.swing.JLabel();
        gameOverExitButton = new javax.swing.JButton();
        scoreDisplayLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the name you want to save your score under");

        username_txtbox.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        username_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtboxActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        viewLeaderboardButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        viewLeaderboardButton.setText("View Leaders");
        viewLeaderboardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        GameOverInfo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        GameOverInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameOverInfo.setText(".");

        noSaveButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        noSaveButton.setText("DON'T SAVE");
        noSaveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        noSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSaveButtonActionPerformed(evt);
            }
        });

        gameOverLabel.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        gameOverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameOverLabel.setText("Game over. The correct number was: ");
        gameOverLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        finalScoreLabel.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        finalScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalScoreLabel.setText("Final Score: "+ NumberGuesser.scoreSaver);

        gameOverExitButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        gameOverExitButton.setText("EXIT");
        gameOverExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gameOverExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameOverExitButtonActionPerformed(evt);
            }
        });

        scoreDisplayLabel.setText(NumberGuesser.scoreSaver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(noSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(viewLeaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(gameOverExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(GameOverInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(finalScoreLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(username_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreDisplayLabel)
                        .addGap(50, 50, 50)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameOverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(gameOverLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalScoreLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scoreDisplayLabel))
                .addGap(18, 18, 18)
                .addComponent(GameOverInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLeaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameOverExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtboxActionPerformed

    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        try{
            String newUser= username_txtbox.getText();
            if (newUser.equals("")){
                GameOverInfo.setText("Error. Enter a valid username");
            } else{
                FileWriter fstream= new FileWriter("leaderboard.txt",true);
                BufferedWriter out = new BufferedWriter(fstream);
                out.write(newUser + "," + NumberGuesser.scoreSaver + "\n");
                out.close();
                GameOverInfo.setText("Sucess! Your score has been saved.");
                noSaveButton.setEnabled(false);
                saveButton.setEnabled(false);
            }
        } catch (Exception e){
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void gameOverExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameOverExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_gameOverExitButtonActionPerformed

    private void noSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSaveButtonActionPerformed
        saveButton.setEnabled(false);
        GameOverInfo.setText("Your score will not be saved.");
    }//GEN-LAST:event_noSaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameOverInfo;
    public javax.swing.JLabel finalScoreLabel;
    private javax.swing.JButton gameOverExitButton;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton noSaveButton;
    private javax.swing.JButton saveButton;
    public javax.swing.JLabel scoreDisplayLabel;
    private javax.swing.JTextField username_txtbox;
    private javax.swing.JButton viewLeaderboardButton;
    // End of variables declaration//GEN-END:variables
}
